baseurl: /JEKLAX
exclude: ['README.md']
permalink: pretty
prose: 
  rooturl: '_posts'
  siteurl: 'https://ssssssssk.github.io/JEKLAX/'
  media: 'media'
  
  metadata: 
    _posts:
    - name: title
      field: 
        element: text
    - name: artist
      field: 
        element: text
