baseurl: /JEKLAX
exclude: ['README.md']
permalink: pretty
prose: 
  rooturl: '_posts'
  siteurl: 'https://ssssssssk.github.io/JEKLAX/'
  media: 'media'
  ignore:
	- index.md
	- _config.yml
	- /_layouts
	- /_includes
  metadata: 
    _posts:
    	- name: title
      		field: 
				element: "text"
				label: "title"
    	- name: artist
      		field: 
        		element: "text"
				label: "artist"
