baseurl: /JEKLAX
exclude: ['README.md']

prose: 
  _posts:
  metadata: 
    - name: "layout"
      field: 
        element: select
        label: "choose what type of email"
        placeholder: "PR or SD"
          options: 
            - name: "pr"
              value: "PR-FINAL"
            - name: "sd"
              value: "SD-FINAL"
    - name: title
      field: 
        element: text
    - name: artist
      field: 
        element: text
