baseurl: /JEKLAX
exclude: ['README.md']
prose: 
 rooturl: '_posts'
 media: 'media'
 metadata: 
  _posts:
   - name: "layout"
     field: 
      element: "select"
      label: "Choose layout"
      options:
       - name: "PR-FINAL" 
         value: "PR-FINAL"
       - name: "SD-FINAL"
         value: "SD-FINAL"
   - name: "artist"
     field: 
      element: "text"
      label: "artist name"
   - name: "show"
     field:
      element: "text"
      label: "show"
   - name: "show-dates"
     field: 
      element: "text"
      label: "start and end dates with &mdash; in between"
   - name: "contact-email"
     field:
      element: "text"
      label: "contact email @laxart.org is presumed so just the name"
   - name: "image-link"
     field: 
      element: "text"
      label: "image link"
   - name: "photo-credit"
     field: 
      element: "text"
      label: "photo credit full text"
   - name: "link-onsite"
     field:
      element: "text"
      label: "Link to show on website"
   - name: "category"
     field: 
      element: "select"
      label: "select category"
      options:
       - name: "Press Release" 
         value: "press"
       - name: "Save The Date"
         value: "dates"